"""Chat and conversation schemas."""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class SourceAttribution(BaseModel):
    """Source attribution chunk citation."""
    document_id: str = Field(..., description="Unique ID of the source document")
    filename: str = Field(..., description="Name of the source document")
    page_number: Optional[int] = Field(None, description="Page number if applicable, or None")
    chunk_id: str = Field(..., description="Unique ID of the retrieved chunk")
    chunk_index: Optional[int] = Field(None, description="Deterministic chunk index")
    score: float = Field(..., description="Cosine relevance similarity score")
    content_snippet: Optional[str] = Field(None, description="Short snippet of retrieved text")


class ChatRequest(BaseModel):
    """Chat request payload."""
    question: str = Field(..., min_length=1, description="User question or query")
    conversation_id: Optional[str] = Field(None, description="Existing conversation ID for context, or null to start new")
    document_ids: List[str] = Field(default_factory=list, description="Optional document IDs to restrict retrieval to")
    similarity_threshold: Optional[float] = Field(None, description="Optional override for similarity cutoff")
    top_k: Optional[int] = Field(None, description="Optional override for number of retrieved chunks")


class ChatResponse(BaseModel):
    """Grounded chat response payload with source attribution and latency metrics."""
    answer: str = Field(..., description="Grounded answer generated by LLM")
    conversation_id: str = Field(..., description="Active conversation ID")
    sources: List[SourceAttribution] = Field(default_factory=list, description="Retrieved source attributions")
    retrieval_latency_ms: Optional[float] = Field(None, description="Retrieval latency in milliseconds")
    generation_latency_ms: Optional[float] = Field(None, description="Generation latency in milliseconds")
    total_latency_ms: Optional[float] = Field(None, description="End-to-end latency in milliseconds")
    abstention: bool = Field(default=False, description="True if system abstained due to lack of evidence")


class MessageResponse(BaseModel):
    """Individual conversation message representation."""
    id: str
    conversation_id: str
    role: str
    content: str
    created_at: datetime

    model_config = {"from_attributes": True}


class ConversationResponse(BaseModel):
    """Conversation history representation."""
    id: str
    user_id: str
    title: str
    messages: List[MessageResponse] = Field(default_factory=list)
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}
